[[bin]]
name = "bin"
path = "src/bin.rs"

[build-dependencies]
cc = {version= "*", features=['parallel']}
shellexpand = "*"
which = "*"

[dependencies]
stdweb = "*"
wasm-bindgen = "*"
wasm-bindgen-futures = "*"
js-sys = "*"
wasm-timer = "*"
console_error_panic_hook = "*"
libc = "*"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[package]
name = "rust_wasm_duckdb"
version = "0.1.0"
authors = ["Elliana <me@mause.me>"]
edition = "2018"
description = "A test to integrate the wasm version of duckdb with rust in the browser"
repository = "https://github.com/Mause/rust_wasm_duckdb"
license = "MIT"
