[package]
name = "rust_wasm_duckdb"
version = "0.1.0"
authors = ["Elliana <me@mause.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "*"
js-sys = "*"
