[tasks.build]
clear = true
dependencies = ['prebuild']
command = "cargo"
args = ["web", "build", "--target", "wasm32-unknown-emscripten"]

[tasks.prebuild]
command = "cargo"
args = ["script", "setup"]

[tasks.test]
clear = true
dependencies = ['build']
command = "cargo"
args = ["web", "test", "--node"]
