[tasks.build]
clear = true
dependencies = ['prebuild']
command = "cargo"
args = ["build", "--tests", "--target", "wasm32-unknown-emscripten"]

[tasks.deploy]
dependencies = ["ci-flow"]
command = "cargo"
args = ["web", "deploy", "--use-system-emscripten"]

[tasks.prebuild]
condition = { files_not_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/target/duckdb.wasm", "${CARGO_MAKE_WORKING_DIRECTORY}/target/duckdb.hpp"] }
script_runner = "@rust"
script = { file = "setup.rs" }

[tasks.test]
clear = true
dependencies = ['build']
command = "cargo"
args = ["web", "test", "--nodejs", "--use-system-emscripten"]
