name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  PROD_DEPLOY: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: deploy
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -g vercel
      - run: vercel link --confirm --token ${{ secrets.VERCEL_TOKEN }}
      - if: ${{ env.PROD_DEPLOY == 'false' }}
        run: vercel deploy . --token ${{ secrets.VERCEL_TOKEN }}
      - if: ${{ env.PROD_DEPLOY == 'true' }}
        run: vercel deploy . --token ${{ secrets.VERCEL_TOKEN }} --prod

  build:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
        target: wasm32-unknown-emscripten
    - uses: Swatinem/rust-cache@v1
    - name: Install rust script
      uses: actions-rs/install@v0.1
      with:
        crate: rust-script
        version: latest
        use-tool-cache: true
    - name: Install cargo web
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-web
        version: latest
        use-tool-cache: true
    - name: Install openssl
      run: |
        sudo apt update
        sudo apt-get install pkg-config build-essential libssl-dev --yes
    - uses: davidB/rust-cargo-make@v1
      with:
        version: latest
    - name: Run CI
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: deploy
      env:
        EMMAKEN_CFLAGS: "-s ERROR_ON_UNDEFINED_SYMBOLS=0"
    - uses: actions/upload-artifact@v2
      with:
        name: deploy
        path: target/deploy
