name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v1

    - name: Install openssl
      run: |
        sudo apt update
        sudo apt-get install pkg-config build-essential libssl-dev --yes
    - uses: davidB/rust-cargo-make@v1
      with:
        version: latest
    - name: Run CI
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: ci-flow
