name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: davidB/rust-cargo-make@v1
      with:
        version: latest
    - name: Run CI
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: ci-flow
