name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:


    runs-on: ubuntu-latest
    container:
      image: emscripten/emsdk:latest



    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy


    - name: Install openssl
      run: |
        sudo apt update
        sudo apt-get install build-essential libssl-dev --yes
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
    - name: Run CI
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: ci-flow
